name: 🚀 Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build library
        run: bun run build
        env:
          LIBRE_LINK_EMAIL: ${{ secrets.LIBRE_LINK_EMAIL }}
          LIBRE_LINK_PASSWORD: ${{ secrets.LIBRE_LINK_PASSWORD }}
          LIBRE_LINK_UP_VERSION: ${{ secrets.LIBRE_LINK_UP_VERSION }}

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          LIBRE_LINK_EMAIL: ${{ secrets.LIBRE_LINK_EMAIL }}
          LIBRE_LINK_PASSWORD: ${{ secrets.LIBRE_LINK_PASSWORD }}
          LIBRE_LINK_UP_VERSION: ${{ secrets.LIBRE_LINK_UP_VERSION }}
